name: CMG Programado Update

on:
  schedule:
    # Run daily at 6:00 AM Santiago time (9:00 UTC)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-cmg-programado:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-playwright-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-playwright-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests pytz
          playwright install chromium
          playwright install-deps chromium
      
      - name: Sync CMG Programado from Partner Gist
        run: |
          echo "📊 Syncing CMG Programado from partner's Gist..."
          python scripts/sync_from_partner_gist.py
        timeout-minutes: 2
      
      - name: Optional - Try Direct Scraper
        run: |
          echo "🔍 Attempting direct scraper (optional)..."
          # Try the scraper but don't fail if it doesn't work
          timeout 60 python scripts/cmg_scraper_simple.py || echo "Direct scraper failed (expected)"
        continue-on-error: true
        timeout-minutes: 2
      
      - name: Update GitHub Gist
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "📤 Updating GitHub Gist..."
          python scripts/update_cmg_gist.py
      
      - name: Commit local changes
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the updated local file
          git add data/cmg_programado_history.json
          
          # Commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update CMG Programado historical data [$(date +'%Y-%m-%d %H:%M')]"
            git push
            echo "✅ Changes committed and pushed"
          else
            echo "ℹ️ No changes to commit"
          fi