name: Daily Performance Calculation at 23:59 Chilean Time

on:
  schedule:
    # Run at 23:59 Chilean time (03:59 UTC next day in summer, 02:59 UTC in winter)
    # Using 03:59 UTC as default (Chilean summer time)
    - cron: '59 3 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  calculate-performance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests pytz numpy
      
      - name: Calculate Daily Performance
        timeout-minutes: 5
        run: |
          cd ${{ github.workspace }}
          echo "========================================"
          echo "DAILY PERFORMANCE CALCULATION"
          echo "Time: $(date)"
          echo "========================================"
          
          # Run the performance calculation
          python scripts/daily_performance_calculation.py
          
          echo "========================================"
          echo "Performance calculation completed"
        env:
          PYTHONPATH: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log calculation status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Daily performance calculation completed successfully"
          else
            echo "❌ Daily performance calculation failed"
          fi