name: Daily Optimization at 17:00 Chilean Time

on:
  schedule:
    # Run at 17:00 Chilean time (21:00 UTC in summer, 20:00 UTC in winter)
    # Using 21:00 UTC as default (Chilean summer time)
    - cron: '0 21 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-optimization:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests pytz numpy
      
      - name: Run Daily Optimization
        timeout-minutes: 5
        run: |
          cd ${{ github.workspace }}
          echo "========================================"
          echo "DAILY OPTIMIZATION RUN"
          echo "Time: $(date)"
          echo "========================================"
          
          # Run the optimization
          python scripts/trigger_optimization.py
          
          echo "========================================"
          echo "Optimization completed"
        env:
          PYTHONPATH: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log optimization status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Daily optimization completed successfully"
          else
            echo "❌ Daily optimization failed"
          fi