name: Setup Performance Gists

on:
  workflow_dispatch:

jobs:
  create-gists:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests pytz
      
      - name: Create all Gists
        run: |
          echo "========================================"
          echo "CREATING ALL PERFORMANCE TRACKING GISTS"
          echo "========================================"
          echo ""
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo ""
          
          # Run the gist creation script
          python scripts/create_all_gists.py
          
          # Check if configuration was created
          if [ -f gist_configuration.json ]; then
            echo ""
            echo "📋 Configuration created:"
            cat gist_configuration.json
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update scripts with new Gist IDs
        if: success()
        run: |
          echo "========================================"
          echo "UPDATING SCRIPTS WITH NEW GIST IDS"
          echo "========================================"
          
          # Read the configuration
          if [ -f gist_configuration.json ]; then
            # Extract Gist IDs using Python
            python -c "
import json
with open('gist_configuration.json', 'r') as f:
    config = json.load(f)
    
gists = config.get('gists', {})

# Update CMG Programado script
if 'cmg_programado' in gists:
    gist_id = gists['cmg_programado']['id']
    print(f'Updating CMG Programado Gist ID to: {gist_id}')
    
    with open('scripts/update_cmg_programado.py', 'r') as f:
        content = f.read()
    
    # Replace the placeholder or old ID
    import re
    content = re.sub(r'GIST_ID = [\"'].*?[\"']', f'GIST_ID = \"{gist_id}\"', content)
    
    with open('scripts/update_cmg_programado.py', 'w') as f:
        f.write(content)
    
    print('✅ Updated scripts/update_cmg_programado.py')

# Update optimizer
if 'optimization' in gists:
    gist_id = gists['optimization']['id']
    print(f'Updating Optimization Gist ID to: {gist_id}')
    
    with open('api/optimizer.py', 'r') as f:
        content = f.read()
    
    content = re.sub(r'OPTIMIZATION_GIST_ID = [\"'].*?[\"']', f'OPTIMIZATION_GIST_ID = \"{gist_id}\"', content)
    
    with open('api/optimizer.py', 'w') as f:
        f.write(content)
    
    print('✅ Updated api/optimizer.py')

# Update performance calculator
if 'optimization' in gists and 'performance' in gists:
    opt_id = gists['optimization']['id']
    perf_id = gists['performance']['id']
    print(f'Updating Performance Calculator Gist IDs')
    
    with open('scripts/daily_performance_calculation.py', 'r') as f:
        content = f.read()
    
    content = re.sub(r'OPTIMIZATION_GIST = [\"'].*?[\"']', f'OPTIMIZATION_GIST = \"{opt_id}\"', content)
    content = re.sub(r'PERFORMANCE_GIST = [\"'].*?[\"']', f'PERFORMANCE_GIST = \"{perf_id}\"', content)
    
    with open('scripts/daily_performance_calculation.py', 'w') as f:
        f.write(content)
    
    print('✅ Updated scripts/daily_performance_calculation.py')

print('All scripts updated!')
"
          fi
      
      - name: Commit changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check for changes
          if ! git diff --quiet; then
            git add -A
            git commit -m "🤖 Update Gist IDs from automated setup
            
            Created new Gists:
            - CMG Programado Historical
            - Optimization Results
            - Performance History
            
            Updated all scripts with new IDs"
            git push
            echo "✅ Changes committed and pushed"
          else
            echo "No changes to commit"
          fi
      
      - name: Summary
        if: always()
        run: |
          echo "========================================"
          echo "SETUP COMPLETE!"
          echo "========================================"
          echo ""
          echo "✅ Check your new Gists at:"
          echo "   https://gist.github.com/${{ github.actor }}"
          echo ""
          echo "📝 The following Gists should have been created:"
          echo "   1. cmg_programado_historical.json"
          echo "   2. optimization_results.json"
          echo "   3. performance_history.json"
          echo ""
          echo "🔧 All script files have been updated with the new Gist IDs"